### PR TITLE
Critique

### PR DESCRIPTION
**Pull request by rmlopes**
In response to issue #191.
Using Metamask section: add a link with information about gas for newbies.
View available tasks/Submit your work: hard to say without being able to try the task subsystem.

### CODE REVIEW

**Review by JohnAllen — COMMENTED** [review]
What do you mean "hard to say without being able to try the task subsystem."?

Can you think of any other ways to improve the page?

**Comment by JohnAllen** [comment]
Also, if you would submit a pull request to the main repo and not your fork

**Comment by rmlopes** [comment]
I wrote that because when we follow the link to the task subsystem there are no tasks in there, thus I could not try the instructions or check the references (namely steps 3 in the last two sections).

The page could have a short introduction to distense at the top. Apart from that and the suggestion on the PR) I could not see other improvements, but bear in mind that I am new to distense.

**Comment by rmlopes** [comment]
I have submitted this PR to the distense repo (https://github.com/Distense/distense-ui/pull/210)

At gitcoin I have used a very low gas price so I am not sure the transaction will go through.

**Pull request merged**
